function H = HfunctionEKF(in1,in2,in3,in4)
%HFUNCTIONEKF
%    H = HFUNCTIONEKF(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    27-Jul-2017 10:22:39

ddth1 = in1(1,:);
ddth2 = in1(2,:);
dth1 = in2(1,:);
dth2 = in2(2,:);
g = in4(7,:);
l1 = in4(1,:);
l2 = in4(2,:);
magVecX = in4(8,:);
magVecZ = in4(10,:);
th1 = in3(1,:);
th2 = in3(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = cos(th2);
t5 = sin(th2);
t6 = dth1.^2;
t7 = dth2.^2;
t8 = ddth1.*l1.*t2;
t9 = ddth2.*l2.*t4;
t10 = ddth1.*l1.*t3;
t11 = ddth2.*l2.*t5;
t12 = l1.*t2.*t6;
t13 = l2.*t4.*t7;
t14 = t10+t12;
t19 = l1.*t3.*t6;
t15 = t8-t19;
t16 = t11+t13;
t20 = l2.*t5.*t7;
t17 = t9-t20;
t18 = t10+t11+t12+t13;
H = reshape([dth1.*l1.*t2.^2.*-2.0-dth1.*l1.*t3.^2.*2.0,0.0,1.0,0.0,0.0,dth1.*l1.*t2.*t4.*-2.0-dth1.*l1.*t3.*t5.*2.0,dth1.*l1.*t2.*t5.*-2.0+dth1.*l1.*t3.*t4.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,dth2.*l2.*t4.^2.*-2.0-dth2.*l2.*t5.^2.*2.0,0.0,1.0,0.0,0.0,-g.*t2,-g.*t3,0.0,-magVecX.*t3-magVecZ.*t2,magVecX.*t2-magVecZ.*t3,-t4.*t15-t5.*t14,t4.*t14-t5.*t15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-g.*t4-t4.*t17-t5.*t16+t5.*t18+t4.*(t8+t9-l1.*t3.*t6-l2.*t5.*t7),-g.*t5+t4.*t16-t4.*t18-t5.*t17+t5.*(t8+t9-t19-t20),0.0,-magVecX.*t5-magVecZ.*t4,magVecX.*t4-magVecZ.*t5],[10,4]);
