function update_equations = updateFunctionEKF(in1,in2,in3,in4)
%UPDATEFUNCTIONEKF
%    UPDATE_EQUATIONS = UPDATEFUNCTIONEKF(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    27-Jul-2017 10:22:39

ddth1 = in1(1,:);
ddth2 = in1(2,:);
dth1 = in2(1,:);
dth2 = in2(2,:);
g = in4(7,:);
l1 = in4(1,:);
l2 = in4(2,:);
magVecX = in4(8,:);
magVecZ = in4(10,:);
th1 = in3(1,:);
th2 = in3(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = dth1.^2;
t5 = ddth1.*l1.*t2;
t12 = l1.*t3.*t4;
t6 = t5-t12;
t7 = ddth1.*l1.*t3;
t8 = l1.*t2.*t4;
t9 = t7+t8;
t10 = cos(th2);
t11 = sin(th2);
t13 = dth2.^2;
t14 = ddth2.*l2.*t10;
t15 = t5-t12+t14-l2.*t11.*t13;
t16 = ddth2.*l2.*t11;
t17 = l2.*t10.*t13;
t18 = t7+t8+t16+t17;
update_equations = [-g.*t3+t3.*t6-t2.*t9,g.*t2-t2.*t6-t3.*t9,dth1,magVecX.*t2-magVecZ.*t3,magVecX.*t3+magVecZ.*t2,-g.*t11+t11.*t15-t10.*t18,g.*t10-t10.*t15-t11.*t18,dth2,magVecX.*t10-magVecZ.*t11,magVecX.*t11+magVecZ.*t10];
